## library() calls go here
library(conflicted)
library(dotenv)
library(targets)
library(tarchetypes)
library(tidygraph)
library(ggplot2)
library(ggraph)
library(ICIKendallTau)
library(visualizationQualityControl)
library(magrittr)
library(dplyr)
library(rmarkdown)
library(patchwork)
library(ggforce)
library(metabolomicsUtilities)
library(limma)
library(openxlsx)
suppressPackageStartupMessages(library(SDAMS))
library(dasev)
library(documentNumbering)
library(flextable)
conflict_prefer("set_names", "rlang")
suppressPackageStartupMessages(library(ComplexHeatmap))
ggplot2::theme_set(cowplot::theme_cowplot())
library(quarto)
options(future.fork.enable = TRUE)
library(furrr)
plan(multicore)
library(categoryCompare2)
conflict_prefer("annotation", "categoryCompare2")
