---
title: "Lipid Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source(here::here("packages.R"))
library(dplyr)
library(ggplot2)
library(limma)
library(qvalue)
```

```{r}
limma_test <-
  function(comparisonIndex,
           saveresulttocsv = FALSE,
           y,
           data,
           geneid,
           outdir = '') {
    result = list()
    for (i in comparisonIndex) {
      group <- y[[i]] - 1
      model <- model.matrix( ~ group)
      data1 = data[, match(comparison[[i]], colnames(data))]
      fit <- lmFit(data1, model, maxit = 50)
      lc <- contrasts.fit(fit, c(0, 1))
      eb <- eBayes(lc)
      vv = topTable(eb, sort.by = "none", number = nrow(data1))
      foldchange = 2 ^ (vv$logFC)
      foldchange = vv$logFC
      qv <-
        qvalue(vv$P.Value,
               pi0.method = "bootstrap",
               lambda = seq(0.05, max(vv$P.Value, na.rm = T), 0.05))$qvalues
      zz = data.frame(
        Probeset = geneid,
        foldchange = foldchange,
        p.value = vv$P.Value,
        q.value = qv,
        score = vv$t
      )
      result[[i]] = zz[order(zz$p.value), ]
      if (saveresulttocsv) {
        write.csv(result[[i]],
                  file = file.path(
                    outdir,
                    paste("result.limma.", comparenames[i], ".csv", sep = "")
                  ),
                  row.names = F)
      }
    }
    return(result)
  }
```


Load and transform data

```{r}
tar_load(tag_xlsx)
dt = openxlsx::read.xlsx(tag_xlsx, rowNames = T)
mat = apply(dt, 1, function(x) {
  if (any(x == 0)) {
    minv = min(x[x != 0])
    minv = minv / sqrt(2)
    x[x == 0] = minv
    return(x)
  } else{
    return(x)
  }
  
})

mat = t(mat)
mat = log2(mat)
```

Limma test

```{r}
geneid <- rownames(mat)
group <- rep(c(0, 1), c(10, 10))
model <- model.matrix( ~ group)
fit <- lmFit(mat, model, maxit = 50)
lc <- contrasts.fit(fit, c(0, 1))
eb <- eBayes(lc)
vv = topTable(eb, sort.by = "none", number = nrow(mat))
foldchange = vv$logFC
qv <-
  qvalue(vv$P.Value,
         pi0.method = "bootstrap",
         lambda = seq(0.05, max(vv$P.Value, na.rm = T), 0.05))$qvalues

limma.result = data.frame(
  Probeset = geneid,
  logFC = foldchange,
  p.value = vv$P.Value,
  q.value = qv,
  score = vv$t
)


results <-
  as.data.frame(mat) %>% dplyr::mutate(Probeset = rownames(mat)) %>%
  inner_join(limma.result) %>% arrange(p.value)

DT::datatable(limma.result)

```

Plot figure

```{r}
res = results %>% dplyr::select(c(Probeset, logFC, q.value))
res$x.axis = gsub(".*\\(([0-9]+:[0-9]+).*", "\\1", res$Probeset)
res$y.axis = gsub(".*/FA([0-9]+:[0-9]+).*", "\\1", res$Probeset)

res$x.axis.n = as.numeric(factor(res$x.axis))
res$y.axis.n = as.numeric(factor(res$y.axis))

tt =   levels(factor(res$x.axis))
x.map = 1:length(tt)
names(x.map) = tt

tt = levels(factor(res$y.axis))
y.map = 1:length(tt)
names(y.map) = tt

res = res %>% mutate(p = as.numeric(q.value), delta = as.numeric(logFC))

limits = c(-2, 2)
res$delta[res$delta > limits[2]] = limits[2]
res$delta[res$delta < limits[1]] = limits[1]

res$p_discrete = cut(-log10(res$p), breaks = c(0, 1.3, 4, 8, 12))

res = res %>% dplyr::filter(!is.na(delta))

res.sig = res %>% dplyr::filter(q.value < 0.05)
sig.size = c(2.0, 3.0, 4.0, 5.0, 6.0) * 2
label.dt = data.frame(x = x.map,
                      y = rep(c(-.3, -1.5), length(x.map) / 2),
                      label = names(x.map))

p = res.sig %>% dplyr::filter(!is.na(p)) %>% ggplot(aes(
  x = x.axis.n,
  y = y.axis.n,
  size = (factor(p_discrete)),
  color = delta
)) + geom_point() +
  #scale_color_gradientn(limits = limits,colours=c("darkred","red", "white", "green","darkgreen"))
  scale_color_viridis_c(limits = limits)
p = p + scale_y_continuous(
  labels = names(y.map),
  breaks = y.map,
  expand = c(0.03, 0.05)
) +
  scale_x_continuous(
    labels = names(x.map),
    breaks = x.map,
    expand = c(0.02, 0.02)
  ) +
  scale_size_manual(
    values = sig.size,
    labels = c(">=0.05", "<0.05", "<0.01", "<0.001", "<0.0001", "<0.0001")
  ) + theme_bw()

p = p + theme_linedraw() +
  labs(x = "# of Triglyceride Carbon Atoms : Double Bonds",
       y = "Fatty Acid Substituents",
       size = "p-value",
       color = "") +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    text = element_text(face = 'bold', size = 12),
    legend.title = element_text(size = 10),
    plot.margin = unit(c(.1, .1, 1.5, .1), "cm"),
    legend.position = c(.1, .9),
    axis.title.x = element_text(vjust = -15)
  ) +
  guides(
    color = guide_colourbar(
      direction = "horizontal",
      barwidth = unit(1.2, "in"),
      barheight = unit(.15, "in"),
      ticks.colour = 'black',
      frame.colour = 'black',
      title = "Fold Change",
      title.position = "bottom"
    ),
    size = "none"
  ) +
  theme(axis.text.x = element_blank()) +
  expand_limits(x = 2) +
  annotate(
    "text",
    x = label.dt$x,
    y = label.dt$y,
    label = label.dt$label,
    angle = 90,
    size = 3,
    fontface = "bold"
  ) +
  coord_cartesian(ylim = c(1, 17), clip = "off")

pdf("doc/scatter_heatmap.pdf",
    width = 9,
    height = 5)
p
dev.off()

p

```

